# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20160802_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticicas', to=settings.AUTH_USER_MODEL),
        ),
    ]
