# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('categoria', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('fuente', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='fecha')),
            ],
        ),
    ]
